import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Providers from "@/components/providers";
import { AuthButtons } from "@/components/authenticationButton";
// import { AppSidebar } from "@/components/app-sidebar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger style={{ height: "60px", width: "60px"}} />
            <Providers>
              <div
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{
                  backgroundColor: "transparent",
                  zIndex: 10,
                  position: "relative",
                  alignItems: "stretch",
                }}
                >
                <AuthButtons />
                {children}
              </div>
            </Providers>
          </SidebarProvider>
      </body>
    </html>
  );
}
